// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: control.proto

package control

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NidhoggRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*NidhoggRequest_Tap
	//	*NidhoggRequest_Swipe
	//	*NidhoggRequest_Crop
	Payload       isNidhoggRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NidhoggRequest) Reset() {
	*x = NidhoggRequest{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NidhoggRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NidhoggRequest) ProtoMessage() {}

func (x *NidhoggRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NidhoggRequest.ProtoReflect.Descriptor instead.
func (*NidhoggRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *NidhoggRequest) GetPayload() isNidhoggRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *NidhoggRequest) GetTap() *TapCommand {
	if x != nil {
		if x, ok := x.Payload.(*NidhoggRequest_Tap); ok {
			return x.Tap
		}
	}
	return nil
}

func (x *NidhoggRequest) GetSwipe() *SwipeCommand {
	if x != nil {
		if x, ok := x.Payload.(*NidhoggRequest_Swipe); ok {
			return x.Swipe
		}
	}
	return nil
}

func (x *NidhoggRequest) GetCrop() *CropRequest {
	if x != nil {
		if x, ok := x.Payload.(*NidhoggRequest_Crop); ok {
			return x.Crop
		}
	}
	return nil
}

type isNidhoggRequest_Payload interface {
	isNidhoggRequest_Payload()
}

type NidhoggRequest_Tap struct {
	Tap *TapCommand `protobuf:"bytes,1,opt,name=tap,proto3,oneof"`
}

type NidhoggRequest_Swipe struct {
	Swipe *SwipeCommand `protobuf:"bytes,2,opt,name=swipe,proto3,oneof"`
}

type NidhoggRequest_Crop struct {
	Crop *CropRequest `protobuf:"bytes,3,opt,name=crop,proto3,oneof"`
}

func (*NidhoggRequest_Tap) isNidhoggRequest_Payload() {}

func (*NidhoggRequest_Swipe) isNidhoggRequest_Payload() {}

func (*NidhoggRequest_Crop) isNidhoggRequest_Payload() {}

type TapCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TapCommand) Reset() {
	*x = TapCommand{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TapCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TapCommand) ProtoMessage() {}

func (x *TapCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TapCommand.ProtoReflect.Descriptor instead.
func (*TapCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *TapCommand) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *TapCommand) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type SwipeCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X1            int32                  `protobuf:"varint,1,opt,name=x1,proto3" json:"x1,omitempty"`
	Y1            int32                  `protobuf:"varint,2,opt,name=y1,proto3" json:"y1,omitempty"`
	X2            int32                  `protobuf:"varint,3,opt,name=x2,proto3" json:"x2,omitempty"`
	Y2            int32                  `protobuf:"varint,4,opt,name=y2,proto3" json:"y2,omitempty"`
	DurationMs    int32                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwipeCommand) Reset() {
	*x = SwipeCommand{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwipeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwipeCommand) ProtoMessage() {}

func (x *SwipeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwipeCommand.ProtoReflect.Descriptor instead.
func (*SwipeCommand) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *SwipeCommand) GetX1() int32 {
	if x != nil {
		return x.X1
	}
	return 0
}

func (x *SwipeCommand) GetY1() int32 {
	if x != nil {
		return x.Y1
	}
	return 0
}

func (x *SwipeCommand) GetX2() int32 {
	if x != nil {
		return x.X2
	}
	return 0
}

func (x *SwipeCommand) GetY2() int32 {
	if x != nil {
		return x.Y2
	}
	return 0
}

func (x *SwipeCommand) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type CropRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CropRequest) Reset() {
	*x = CropRequest{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CropRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CropRequest) ProtoMessage() {}

func (x *CropRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CropRequest.ProtoReflect.Descriptor instead.
func (*CropRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *CropRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *CropRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *CropRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CropRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type NidhoggResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Success  bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*NidhoggResponse_ImageData
	Data          isNidhoggResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NidhoggResponse) Reset() {
	*x = NidhoggResponse{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NidhoggResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NidhoggResponse) ProtoMessage() {}

func (x *NidhoggResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NidhoggResponse.ProtoReflect.Descriptor instead.
func (*NidhoggResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *NidhoggResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NidhoggResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *NidhoggResponse) GetData() isNidhoggResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *NidhoggResponse) GetImageData() []byte {
	if x != nil {
		if x, ok := x.Data.(*NidhoggResponse_ImageData); ok {
			return x.ImageData
		}
	}
	return nil
}

type isNidhoggResponse_Data interface {
	isNidhoggResponse_Data()
}

type NidhoggResponse_ImageData struct {
	ImageData []byte `protobuf:"bytes,3,opt,name=image_data,json=imageData,proto3,oneof"`
}

func (*NidhoggResponse_ImageData) isNidhoggResponse_Data() {}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\x13com.project.control\"\xc3\x01\n" +
	"\x0eNidhoggRequest\x123\n" +
	"\x03tap\x18\x01 \x01(\v2\x1f.com.project.control.TapCommandH\x00R\x03tap\x129\n" +
	"\x05swipe\x18\x02 \x01(\v2!.com.project.control.SwipeCommandH\x00R\x05swipe\x126\n" +
	"\x04crop\x18\x03 \x01(\v2 .com.project.control.CropRequestH\x00R\x04cropB\t\n" +
	"\apayload\"(\n" +
	"\n" +
	"TapCommand\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"o\n" +
	"\fSwipeCommand\x12\x0e\n" +
	"\x02x1\x18\x01 \x01(\x05R\x02x1\x12\x0e\n" +
	"\x02y1\x18\x02 \x01(\x05R\x02y1\x12\x0e\n" +
	"\x02x2\x18\x03 \x01(\x05R\x02x2\x12\x0e\n" +
	"\x02y2\x18\x04 \x01(\x05R\x02y2\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x05R\n" +
	"durationMs\"W\n" +
	"\vCropRequest\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\"q\n" +
	"\x0fNidhoggResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12\x1f\n" +
	"\n" +
	"image_data\x18\x03 \x01(\fH\x00R\timageDataB\x06\n" +
	"\x04dataB5Z3github.com/Vancheszz/android-agent/internal/controlb\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_control_proto_goTypes = []any{
	(*NidhoggRequest)(nil),  // 0: com.project.control.NidhoggRequest
	(*TapCommand)(nil),      // 1: com.project.control.TapCommand
	(*SwipeCommand)(nil),    // 2: com.project.control.SwipeCommand
	(*CropRequest)(nil),     // 3: com.project.control.CropRequest
	(*NidhoggResponse)(nil), // 4: com.project.control.NidhoggResponse
}
var file_control_proto_depIdxs = []int32{
	1, // 0: com.project.control.NidhoggRequest.tap:type_name -> com.project.control.TapCommand
	2, // 1: com.project.control.NidhoggRequest.swipe:type_name -> com.project.control.SwipeCommand
	3, // 2: com.project.control.NidhoggRequest.crop:type_name -> com.project.control.CropRequest
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	file_control_proto_msgTypes[0].OneofWrappers = []any{
		(*NidhoggRequest_Tap)(nil),
		(*NidhoggRequest_Swipe)(nil),
		(*NidhoggRequest_Crop)(nil),
	}
	file_control_proto_msgTypes[4].OneofWrappers = []any{
		(*NidhoggResponse_ImageData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
