// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: ratatoskr.proto

package ratatoskr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentCMD_CMDType int32

const (
	AgentCMD_CLICK     AgentCMD_CMDType = 0
	AgentCMD_TYPE_TEXT AgentCMD_CMDType = 1
	AgentCMD_GET_DUMP  AgentCMD_CMDType = 2
)

// Enum value maps for AgentCMD_CMDType.
var (
	AgentCMD_CMDType_name = map[int32]string{
		0: "CLICK",
		1: "TYPE_TEXT",
		2: "GET_DUMP",
	}
	AgentCMD_CMDType_value = map[string]int32{
		"CLICK":     0,
		"TYPE_TEXT": 1,
		"GET_DUMP":  2,
	}
)

func (x AgentCMD_CMDType) Enum() *AgentCMD_CMDType {
	p := new(AgentCMD_CMDType)
	*p = x
	return p
}

func (x AgentCMD_CMDType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentCMD_CMDType) Descriptor() protoreflect.EnumDescriptor {
	return file_ratatoskr_proto_enumTypes[0].Descriptor()
}

func (AgentCMD_CMDType) Type() protoreflect.EnumType {
	return &file_ratatoskr_proto_enumTypes[0]
}

func (x AgentCMD_CMDType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentCMD_CMDType.Descriptor instead.
func (AgentCMD_CMDType) EnumDescriptor() ([]byte, []int) {
	return file_ratatoskr_proto_rawDescGZIP(), []int{3, 0}
}

type ScreenDump struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackageName   string                 `protobuf:"bytes,1,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Nodes         []*UiNode              `protobuf:"bytes,5,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenDump) Reset() {
	*x = ScreenDump{}
	mi := &file_ratatoskr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenDump) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenDump) ProtoMessage() {}

func (x *ScreenDump) ProtoReflect() protoreflect.Message {
	mi := &file_ratatoskr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenDump.ProtoReflect.Descriptor instead.
func (*ScreenDump) Descriptor() ([]byte, []int) {
	return file_ratatoskr_proto_rawDescGZIP(), []int{0}
}

func (x *ScreenDump) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *ScreenDump) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ScreenDump) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ScreenDump) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ScreenDump) GetNodes() []*UiNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type UiNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      int32                  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	ResourceId    string                 `protobuf:"bytes,4,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ClassName     string                 `protobuf:"bytes,5,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	IsClickable   bool                   `protobuf:"varint,6,opt,name=is_clickable,json=isClickable,proto3" json:"is_clickable,omitempty"`
	Bounds        *Rect                  `protobuf:"bytes,7,opt,name=bounds,proto3" json:"bounds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UiNode) Reset() {
	*x = UiNode{}
	mi := &file_ratatoskr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UiNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UiNode) ProtoMessage() {}

func (x *UiNode) ProtoReflect() protoreflect.Message {
	mi := &file_ratatoskr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UiNode.ProtoReflect.Descriptor instead.
func (*UiNode) Descriptor() ([]byte, []int) {
	return file_ratatoskr_proto_rawDescGZIP(), []int{1}
}

func (x *UiNode) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UiNode) GetParentId() int32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *UiNode) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *UiNode) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *UiNode) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *UiNode) GetIsClickable() bool {
	if x != nil {
		return x.IsClickable
	}
	return false
}

func (x *UiNode) GetBounds() *Rect {
	if x != nil {
		return x.Bounds
	}
	return nil
}

type Rect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Left          int32                  `protobuf:"varint,1,opt,name=left,proto3" json:"left,omitempty"`
	Right         int32                  `protobuf:"varint,2,opt,name=right,proto3" json:"right,omitempty"`
	Top           int32                  `protobuf:"varint,3,opt,name=top,proto3" json:"top,omitempty"`
	Bottom        int32                  `protobuf:"varint,4,opt,name=bottom,proto3" json:"bottom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rect) Reset() {
	*x = Rect{}
	mi := &file_ratatoskr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rect) ProtoMessage() {}

func (x *Rect) ProtoReflect() protoreflect.Message {
	mi := &file_ratatoskr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rect.ProtoReflect.Descriptor instead.
func (*Rect) Descriptor() ([]byte, []int) {
	return file_ratatoskr_proto_rawDescGZIP(), []int{2}
}

func (x *Rect) GetLeft() int32 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *Rect) GetRight() int32 {
	if x != nil {
		return x.Right
	}
	return 0
}

func (x *Rect) GetTop() int32 {
	if x != nil {
		return x.Top
	}
	return 0
}

func (x *Rect) GetBottom() int32 {
	if x != nil {
		return x.Bottom
	}
	return 0
}

type AgentCMD struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          AgentCMD_CMDType       `protobuf:"varint,1,opt,name=type,proto3,enum=com.project.ratatoskr.AgentCMD_CMDType" json:"type,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCMD) Reset() {
	*x = AgentCMD{}
	mi := &file_ratatoskr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCMD) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCMD) ProtoMessage() {}

func (x *AgentCMD) ProtoReflect() protoreflect.Message {
	mi := &file_ratatoskr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCMD.ProtoReflect.Descriptor instead.
func (*AgentCMD) Descriptor() ([]byte, []int) {
	return file_ratatoskr_proto_rawDescGZIP(), []int{3}
}

func (x *AgentCMD) GetType() AgentCMD_CMDType {
	if x != nil {
		return x.Type
	}
	return AgentCMD_CLICK
}

func (x *AgentCMD) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *AgentCMD) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_ratatoskr_proto protoreflect.FileDescriptor

const file_ratatoskr_proto_rawDesc = "" +
	"\n" +
	"\x0fratatoskr.proto\x12\x15com.project.ratatoskr\"\xb0\x01\n" +
	"\n" +
	"ScreenDump\x12!\n" +
	"\fpackage_name\x18\x01 \x01(\tR\vpackageName\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x123\n" +
	"\x05nodes\x18\x05 \x03(\v2\x1d.com.project.ratatoskr.UiNodeR\x05nodes\"\xe1\x01\n" +
	"\x06UiNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x05R\bparentId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1f\n" +
	"\vresource_id\x18\x04 \x01(\tR\n" +
	"resourceId\x12\x1d\n" +
	"\n" +
	"class_name\x18\x05 \x01(\tR\tclassName\x12!\n" +
	"\fis_clickable\x18\x06 \x01(\bR\visClickable\x123\n" +
	"\x06bounds\x18\a \x01(\v2\x1b.com.project.ratatoskr.RectR\x06bounds\"Z\n" +
	"\x04Rect\x12\x12\n" +
	"\x04left\x18\x01 \x01(\x05R\x04left\x12\x14\n" +
	"\x05right\x18\x02 \x01(\x05R\x05right\x12\x10\n" +
	"\x03top\x18\x03 \x01(\x05R\x03top\x12\x16\n" +
	"\x06bottom\x18\x04 \x01(\x05R\x06bottom\"\xb1\x01\n" +
	"\bAgentCMD\x12;\n" +
	"\x04type\x18\x01 \x01(\x0e2'.com.project.ratatoskr.AgentCMD.CMDTypeR\x04type\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"1\n" +
	"\aCMDType\x12\t\n" +
	"\x05CLICK\x10\x00\x12\r\n" +
	"\tTYPE_TEXT\x10\x01\x12\f\n" +
	"\bGET_DUMP\x10\x02BW\n" +
	"\x15com.project.ratatoskrP\x01Z<module github.com/Vancheszz/android-agent/internal/ratatoskrb\x06proto3"

var (
	file_ratatoskr_proto_rawDescOnce sync.Once
	file_ratatoskr_proto_rawDescData []byte
)

func file_ratatoskr_proto_rawDescGZIP() []byte {
	file_ratatoskr_proto_rawDescOnce.Do(func() {
		file_ratatoskr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ratatoskr_proto_rawDesc), len(file_ratatoskr_proto_rawDesc)))
	})
	return file_ratatoskr_proto_rawDescData
}

var file_ratatoskr_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ratatoskr_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ratatoskr_proto_goTypes = []any{
	(AgentCMD_CMDType)(0), // 0: com.project.ratatoskr.AgentCMD.CMDType
	(*ScreenDump)(nil),    // 1: com.project.ratatoskr.ScreenDump
	(*UiNode)(nil),        // 2: com.project.ratatoskr.UiNode
	(*Rect)(nil),          // 3: com.project.ratatoskr.Rect
	(*AgentCMD)(nil),      // 4: com.project.ratatoskr.AgentCMD
}
var file_ratatoskr_proto_depIdxs = []int32{
	2, // 0: com.project.ratatoskr.ScreenDump.nodes:type_name -> com.project.ratatoskr.UiNode
	3, // 1: com.project.ratatoskr.UiNode.bounds:type_name -> com.project.ratatoskr.Rect
	0, // 2: com.project.ratatoskr.AgentCMD.type:type_name -> com.project.ratatoskr.AgentCMD.CMDType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ratatoskr_proto_init() }
func file_ratatoskr_proto_init() {
	if File_ratatoskr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ratatoskr_proto_rawDesc), len(file_ratatoskr_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ratatoskr_proto_goTypes,
		DependencyIndexes: file_ratatoskr_proto_depIdxs,
		EnumInfos:         file_ratatoskr_proto_enumTypes,
		MessageInfos:      file_ratatoskr_proto_msgTypes,
	}.Build()
	File_ratatoskr_proto = out.File
	file_ratatoskr_proto_goTypes = nil
	file_ratatoskr_proto_depIdxs = nil
}
